version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"
    volumes:
        - postgres:/var/lib/postgresql/data
  web:
    depends_on:
        - "postgres"
    build: .
    ports:
        - "8090:8090"
    environment:
        - POSTGRES_URI=postgresql://username:password@postgres:5432/avito
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "3000:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/openapi.yaml
volumes:
  postgres: